steps:
  # Build the Docker image with caching
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build',
      '--cache-from', 'australia-southeast1-docker.pkg.dev/$PROJECT_ID/gcr.io/reggie-frontend:latest',
      '--build-arg', 'NEXT_PUBLIC_DEFAULT_AGENT_ID=${_NEXT_PUBLIC_DEFAULT_AGENT_ID}',
      '--build-arg', 'NEXT_PUBLIC_API_ORIGIN=${_NEXT_PUBLIC_API_ORIGIN}',
      '--build-arg', 'NEXT_PUBLIC_API_BASE_URL=${_NEXT_PUBLIC_API_BASE_URL}',
      '--build-arg', 'NEXT_PUBLIC_NANGO_API_URL=${_NEXT_PUBLIC_NANGO_API_URL}',
      '--build-arg', 'NEXT_PUBLIC_NANGO_SECRET_KEY=${_NEXT_PUBLIC_NANGO_SECRET_KEY}',
      '--build-arg', 'NEXT_PUBLIC_NANGO_BASE_URL=${_NEXT_PUBLIC_NANGO_BASE_URL}',
      '--build-arg', 'COLLABORATION_WS_URL=${_COLLABORATION_WS_URL}',
      '--build-arg', 'NEXT_PUBLIC_SENTRY_DSN=${_NEXT_PUBLIC_SENTRY_DSN}',
      '--build-arg', 'SENTRY_AUTH_TOKEN=${_SENTRY_AUTH_TOKEN}',
      '-t', 'australia-southeast1-docker.pkg.dev/$PROJECT_ID/gcr.io/reggie-frontend:$COMMIT_SHA',
      '-t', 'australia-southeast1-docker.pkg.dev/$PROJECT_ID/gcr.io/reggie-frontend:latest',
      '.'
    ]

  # Push the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'australia-southeast1-docker.pkg.dev/$PROJECT_ID/gcr.io/reggie-frontend:$COMMIT_SHA']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'australia-southeast1-docker.pkg.dev/$PROJECT_ID/gcr.io/reggie-frontend:latest']

  # Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args: [
      'run', 'deploy', 'reggie-frontend',
      '--image', 'australia-southeast1-docker.pkg.dev/$PROJECT_ID/gcr.io/reggie-frontend:$COMMIT_SHA',
      '--region', '${_REGION}',
      '--platform', 'managed',
      '--allow-unauthenticated',
      '--port', '3000',
      '--memory', '1Gi',
      '--cpu', '1',
      '--min-instances', '0',
      '--max-instances', '10',
      '--concurrency', '100',
      '--timeout', '300',
      '--set-env-vars', 'NEXT_PUBLIC_DEFAULT_AGENT_ID=${_NEXT_PUBLIC_DEFAULT_AGENT_ID}',
      '--set-env-vars', 'NEXT_PUBLIC_API_ORIGIN=${_NEXT_PUBLIC_API_ORIGIN}',
      '--set-env-vars', 'NEXT_PUBLIC_API_BASE_URL=${_NEXT_PUBLIC_API_BASE_URL}',
      '--set-env-vars', 'NEXT_PUBLIC_NANGO_API_URL=${_NEXT_PUBLIC_NANGO_API_URL}',
      '--set-env-vars', 'NEXT_PUBLIC_NANGO_SECRET_KEY=${_NEXT_PUBLIC_NANGO_SECRET_KEY}',
      '--set-env-vars', 'NEXT_PUBLIC_NANGO_BASE_URL=${_NEXT_PUBLIC_NANGO_BASE_URL}',
      '--set-env-vars', 'COLLABORATION_WS_URL=${_COLLABORATION_WS_URL}',
      '--set-env-vars', 'NEXT_PUBLIC_SENTRY_DSN=${_NEXT_PUBLIC_SENTRY_DSN}',
      '--set-env-vars', 'SENTRY_AUTH_TOKEN=${_SENTRY_AUTH_TOKEN}',
      '--set-env-vars', 'NODE_ENV=production'
    ]

# Substitution variables (set in Cloud Build trigger)
substitutions:
  _NEXT_PUBLIC_DEFAULT_AGENT_ID: ''
  _NEXT_PUBLIC_API_ORIGIN: ''
  _NEXT_PUBLIC_API_BASE_URL: ''
  _NEXT_PUBLIC_NANGO_API_URL: ''
  _NEXT_PUBLIC_NANGO_SECRET_KEY: ''
  _NEXT_PUBLIC_NANGO_BASE_URL: ''
  _COLLABORATION_WS_URL: ''
  _NEXT_PUBLIC_SENTRY_DSN: ''
  _SENTRY_AUTH_TOKEN: ''
  _REGION: 'us-central1'

options:
  logging: CLOUD_LOGGING_ONLY
  machineType: 'E2_HIGHCPU_8'  # Faster builds
