steps:
  # Build the Docker image with caching
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build',
      '--cache-from', 'australia-southeast1-docker.pkg.dev/$PROJECT_ID/gcr.io/opie-frontend:latest',
      '--build-arg', 'NEXT_PUBLIC_DEFAULT_AGENT_ID=${_NEXT_PUBLIC_DEFAULT_AGENT_ID}',
      '--build-arg', 'NEXT_PUBLIC_API_ORIGIN=${_NEXT_PUBLIC_API_ORIGIN}',
      '--build-arg', 'NEXT_PUBLIC_API_BASE_URL=${_NEXT_PUBLIC_API_BASE_URL}',
      '--build-arg', 'NEXT_PUBLIC_NANGO_API_URL=${_NEXT_PUBLIC_NANGO_API_URL}',
      '--build-arg', 'NEXT_PUBLIC_NANGO_SECRET_KEY=${_NEXT_PUBLIC_NANGO_SECRET_KEY}',
      '--build-arg', 'NEXT_PUBLIC_NANGO_BASE_URL=${_NEXT_PUBLIC_NANGO_BASE_URL}',
      '--build-arg', 'COLLABORATION_WS_URL=${_COLLABORATION_WS_URL}',
      '--build-arg', 'NEXT_PUBLIC_SENTRY_DSN=${_NEXT_PUBLIC_SENTRY_DSN}',
      '--build-arg', 'SENTRY_AUTH_TOKEN=${_SENTRY_AUTH_TOKEN}',
      '-t', 'australia-southeast1-docker.pkg.dev/$PROJECT_ID/gcr.io/opie-frontend:$COMMIT_SHA',
      '-t', 'australia-southeast1-docker.pkg.dev/$PROJECT_ID/gcr.io/opie-frontend:latest',
      '.'
    ]

  # Push the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'australia-southeast1-docker.pkg.dev/$PROJECT_ID/gcr.io/opie-frontend:$COMMIT_SHA']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'australia-southeast1-docker.pkg.dev/$PROJECT_ID/gcr.io/opie-frontend:latest']

  # Deploy to VM using gcloud compute ssh
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        # Deploy to VM
        gcloud compute ssh ${_VM_INSTANCE_NAME} \
          --zone=${_VM_ZONE} \
          --project=$PROJECT_ID \
          --command="
            IMAGE_FRONTEND=australia-southeast1-docker.pkg.dev/$PROJECT_ID/gcr.io/opie-frontend:$COMMIT_SHA
            mkdir -p ~/frontend
            cd ~/frontend
            
            # Create docker-compose.yml
            cat > docker-compose.yml << 'EOF'
        version: '3.8'
        services:
          frontend:
            container_name: frontend-app
            image: \${IMAGE_FRONTEND}
            ports:
              - \"5173:3000\"
            restart: unless-stopped
            environment:
              - NODE_ENV=production
              - NEXT_PUBLIC_DEFAULT_AGENT_ID=${_NEXT_PUBLIC_DEFAULT_AGENT_ID}
              - NEXT_PUBLIC_API_ORIGIN=${_NEXT_PUBLIC_API_ORIGIN}
              - NEXT_PUBLIC_API_BASE_URL=${_NEXT_PUBLIC_API_BASE_URL}
              - NEXT_PUBLIC_NANGO_API_URL=${_NEXT_PUBLIC_NANGO_API_URL}
              - NEXT_PUBLIC_NANGO_SECRET_KEY=${_NEXT_PUBLIC_NANGO_SECRET_KEY}
              - NEXT_PUBLIC_NANGO_BASE_URL=${_NEXT_PUBLIC_NANGO_BASE_URL}
              - COLLABORATION_WS_URL=${_COLLABORATION_WS_URL}
              - NEXT_PUBLIC_SENTRY_DSN=${_NEXT_PUBLIC_SENTRY_DSN}
              - SENTRY_AUTH_TOKEN=${_SENTRY_AUTH_TOKEN}
        EOF
            
            # Update image in docker-compose.yml
            sed -i \"s|\\\${IMAGE_FRONTEND}|\$IMAGE_FRONTEND|g\" docker-compose.yml
            
            # Pull and restart
            sudo docker-compose pull
            sudo docker-compose down --remove-orphans || true
            sudo docker-compose up -d --remove-orphans
            sudo docker image prune -f
          "

# Substitution variables (set in Cloud Build trigger)
substitutions:
  _NEXT_PUBLIC_DEFAULT_AGENT_ID: ''
  _NEXT_PUBLIC_API_ORIGIN: ''
  _NEXT_PUBLIC_API_BASE_URL: ''
  _NEXT_PUBLIC_NANGO_API_URL: ''
  _NEXT_PUBLIC_NANGO_SECRET_KEY: ''
  _NEXT_PUBLIC_NANGO_BASE_URL: ''
  _COLLABORATION_WS_URL: ''
  _NEXT_PUBLIC_SENTRY_DSN: ''
  _SENTRY_AUTH_TOKEN: ''
  _VM_INSTANCE_NAME: ''
  _VM_ZONE: ''

options:
  logging: CLOUD_LOGGING_ONLY
  machineType: 'E2_HIGHCPU_8'  # Faster builds
