version: '3.8'
services:
  frontend:
    container_name: opie-frontend
    image: ${IMAGE_FRONTEND}
    ports:
      - "5173:3000"
    env_file:
      - .env.frontend
    restart: unless-stopped
    environment:
      - NODE_ENV=production
