# Cloudflare Pages configuration for Reggie Frontend
name = "reggie-frontend"
compatibility_date = "2024-12-01"
compatibility_flags = ["nodejs_compat"]

# Cloudflare Pages needs the Next on Pages build artifacts
pages_build_output_dir = ".vercel/output/static"

# Production environment
[env.production]
name = "reggie-frontend"

# Preview (aka staging) environment for Cloudflare Pages
[env.preview]
name = "reggie-frontend-preview"
