# Cloudflare Pages configuration for Opie Frontend
name = "opie-frontend"
compatibility_date = "2024-01-01"

# Production environment
[env.production]
name = "opie-frontend"

# Staging environment
[env.staging]
name = "opie-frontend-staging"

# Cloudflare Pages build configuration
# This tells Cloudflare Pages where to find the built static files
pages_build_output_dir = "out"
